language: 'elixir'
sudo: false
elixir: '1.7'
otp_release: '21.1'
install:
  - 'mix local.hex --force'
  - 'mix local.rebar --force'
  - 'cd parser_sdk && mix deps.get && mix compile'
script:
  - 'pwd'
  - 'cd'
  - 'pwd'
  - 'sh test.sh'